[package]
name = "bin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
instructions = { path = "../instructions" }
util_macros = { path = "../util_macros" }
runtime-constants = { path = "../runtime-constants" }
